import { Tenant, User, Staff, Service, Appointment, Transaction, AutomationLog } from '@/types';

// Tenant: Bella Güzellik & Tırnak Stüdyosu (Powered by UCE Randevu)
export const initialTenant: Tenant = {
  id: 'tenant-1',
  name: 'Bella Tırnak & Güzellik Stüdyosu',
  slug: 'glamour-nail', // Route compatibility
  phone: '+90 212 234 56 78',
  address: 'Bağdat Caddesi No:142 Kadıköy, İstanbul',
  currency: '₺',
  plan: 'PRO',
  isActive: true,
  whatsappConnected: true,
  whatsappNumber: '+90 532 123 45 67',
  instagramConnected: true,
  instagramHandle: '@bellanailstudio',
  createdAt: '2026-01-01',
};

// Staff Members
export const initialStaff: Staff[] = [
  {
    id: 'staff-1',
    tenantId: 'tenant-1',
    staffCode: 'ST-01',
    name: 'Zeynep Kaya',
    title: 'Kıdemli Protez Tırnak Uzmanı',
    phone: '+90 533 111 22 33',
    avatarColor: 'bg-blue-600',
    isActive: true,
    commissionRate: 40,
    workingHours: {
      start: '09:00',
      end: '19:00',
      days: [1, 2, 3, 4, 5, 6],
    },
  },
  {
    id: 'staff-2',
    tenantId: 'tenant-1',
    staffCode: 'ST-02',
    name: 'Merve Demir',
    title: 'Nail Artist & Kalıcı Oje Uzmanı',
    phone: '+90 533 222 33 44',
    avatarColor: 'bg-indigo-600',
    isActive: true,
    commissionRate: 35,
    workingHours: {
      start: '10:00',
      end: '20:00',
      days: [1, 2, 3, 4, 5, 6],
    },
  },
  {
    id: 'staff-3',
    tenantId: 'tenant-1',
    staffCode: 'ST-03',
    name: 'Ayşe Yılmaz',
    title: 'Medikal Manikür & Pedikür',
    phone: '+90 533 333 44 55',
    avatarColor: 'bg-emerald-600',
    isActive: true,
    commissionRate: 35,
    workingHours: {
      start: '09:00',
      end: '18:00',
      days: [2, 3, 4, 5, 6, 7],
    },
  },
];

// Service Catalog
export const initialServices: Service[] = [
  {
    id: 'srv-1',
    tenantId: 'tenant-1',
    name: 'Jel Protez Tırnak (Yeni Set)',
    category: 'Protez Tırnak',
    durationMinutes: 60,
    price: 750,
    description: 'Şablon uzatma, tipsiz jel mimarisi ve kuru manikür dahil.',
    isActive: true,
  },
  {
    id: 'srv-2',
    tenantId: 'tenant-1',
    name: 'Kalıcı Oje & Kuru Manikür',
    category: 'Manikür',
    durationMinutes: 45,
    price: 450,
    description: 'Kütikül temizliği, tırnak şekillendirme ve 3-4 hafta kalıcı renk uygulaması.',
    isActive: true,
  },
  {
    id: 'srv-3',
    tenantId: 'tenant-1',
    name: 'Nail Art / Özel Tasarım',
    category: 'Tasarım',
    durationMinutes: 30,
    price: 250,
    description: 'French, ombre, taş dizimi veya el çizimi soyut desenler.',
    isActive: true,
  },
  {
    id: 'srv-4',
    tenantId: 'tenant-1',
    name: 'Medikal Spa Pedikür',
    category: 'Pedikür',
    durationMinutes: 60,
    price: 650,
    description: 'Buharlı ayak banyosu, topuk çatlak bakımı ve peeling masajı.',
    isActive: true,
  },
  {
    id: 'srv-5',
    tenantId: 'tenant-1',
    name: 'İpek Kirpik & Lifting',
    category: 'Bakım',
    durationMinutes: 60,
    price: 800,
    description: 'Doğal vizon kirpik ekleme ve keratin vitamin bakımı.',
    isActive: true,
  },
  {
    id: 'srv-6',
    tenantId: 'tenant-1',
    name: 'Kaş Tasarımı & Laminasyon',
    category: 'Bakım',
    durationMinutes: 45,
    price: 400,
    description: 'Altın oran kaş alımı, şekillendirme ve 6 haftalık laminasyon sabitleme.',
    isActive: true,
  },
];

const today = new Date().toISOString().split('T')[0];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    tenantId: 'tenant-1',
    customerName: 'Selin Aydın',
    customerPhone: '0532 111 22 33',
    staffId: 'staff-1', // Zeynep Kaya (ST-01)
    serviceId: 'srv-1', // Jel Protez
    date: today,
    startTime: '10:00',
    endTime: '11:00',
    status: 'COMPLETED',
    price: 750,
    paymentMethod: 'CREDIT_CARD',
    whatsappReminderSent: true,
    notes: 'Kısa badem tırnak formu istiyor.',
    createdAt: `${today} 09:15`,
  },
  {
    id: 'apt-2',
    tenantId: 'tenant-1',
    customerName: 'Büşra Çelik',
    customerPhone: '0533 222 44 55',
    staffId: 'staff-1', // Zeynep Kaya (ST-01)
    serviceId: 'srv-2', // Kalıcı Oje
    date: today,
    startTime: '13:00',
    endTime: '13:45',
    status: 'CONFIRMED',
    price: 450,
    paymentMethod: 'UNPAID',
    whatsappReminderSent: true,
    notes: 'Bordo renk tonu tercih edecek.',
    createdAt: `${today} 10:00`,
  },
  {
    id: 'apt-3',
    tenantId: 'tenant-1',
    customerName: 'Ece Karaca',
    customerPhone: '0535 333 55 66',
    staffId: 'staff-2', // Merve Demir (ST-02)
    serviceId: 'srv-3', // Nail Art
    date: today,
    startTime: '11:30',
    endTime: '12:00',
    status: 'CONFIRMED',
    price: 250,
    paymentMethod: 'CASH',
    whatsappReminderSent: true,
    notes: '2 parmağa minimal çiçek deseni.',
    createdAt: `${today} 10:30`,
  },
  {
    id: 'apt-4',
    tenantId: 'tenant-1',
    customerName: 'Dilek Yılmaz',
    customerPhone: '0530 444 66 77',
    staffId: 'staff-3', // Ayşe Yılmaz (ST-03)
    serviceId: 'srv-4', // Spa Pedikür
    date: today,
    startTime: '14:00',
    endTime: '15:00',
    status: 'CONFIRMED',
    price: 650,
    paymentMethod: 'UNPAID',
    whatsappReminderSent: true,
    notes: 'Düzenli müşteri.',
    createdAt: `${today} 11:00`,
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: 'txn-1',
    tenantId: 'tenant-1',
    type: 'INCOME',
    category: 'Hizmet Ödemesi',
    amount: 750,
    paymentMethod: 'CREDIT_CARD',
    description: 'Selin Aydın - Jel Protez Tırnak (Zeynep K.)',
    staffId: 'staff-1',
    appointmentId: 'apt-1',
    date: today,
    createdAt: `${today} 11:05`,
  },
  {
    id: 'txn-2',
    tenantId: 'tenant-1',
    type: 'INCOME',
    category: 'Hizmet Ödemesi',
    amount: 450,
    paymentMethod: 'CASH',
    description: 'Demet S. - Kalıcı Oje & Manikür',
    date: today,
    createdAt: `${today} 12:00`,
  },
  {
    id: 'txn-3',
    tenantId: 'tenant-1',
    type: 'INCOME',
    category: 'Ürün Satışı',
    amount: 350,
    paymentMethod: 'HAVALE',
    description: 'Tırnak Bakım Serumu & Kütikül Yağı',
    date: today,
    createdAt: `${today} 12:30`,
  },
  {
    id: 'txn-4',
    tenantId: 'tenant-1',
    type: 'EXPENSE',
    category: 'Malzeme Alımı',
    amount: 850,
    paymentMethod: 'CREDIT_CARD',
    description: 'Tırnak Jeli, Freze Uçları ve Dezenfektan Alımı',
    date: today,
    createdAt: `${today} 09:30`,
  },
  {
    id: 'txn-5',
    tenantId: 'tenant-1',
    type: 'EXPENSE',
    category: 'Mutfak & İkram',
    amount: 180,
    paymentMethod: 'CASH',
    description: 'Kahve, Maden Suyu ve Çay İkramları',
    date: today,
    createdAt: `${today} 10:15`,
  },
];

export const initialAutomationLogs: AutomationLog[] = [
  {
    id: 'log-1',
    tenantId: 'tenant-1',
    type: 'WHATSAPP',
    recipient: '+90 532 111 22 33 (Selin Aydın)',
    message: 'Sayın Selin Hanım, Bella Güzellik Stüdyosu randevunuz Zeynep Kaya ile saat 10:00 için teyit edilmiştir. Bizi tercih ettiğiniz için teşekkür ederiz.',
    status: 'DELIVERED',
    createdAt: `${today} 09:15`,
  },
  {
    id: 'log-2',
    tenantId: 'tenant-1',
    type: 'WHATSAPP',
    recipient: '+90 533 222 44 55 (Büşra Çelik)',
    message: 'Randevu Hatırlatma: Bugün saat 13:00 de Kalıcı Oje randevunuz bulunmaktadır. Gecikme durumunda lütfen bize bilgi veriniz.',
    status: 'DELIVERED',
    createdAt: `${today} 11:30`,
  },
  {
    id: 'log-3',
    tenantId: 'tenant-1',
    type: 'INSTAGRAM',
    recipient: '@ece.karaca',
    message: 'Merhaba! Randevu almak ve uzmanlarımızın boş saatlerini incelemek için linkimize tıklayabilirsiniz: https://ucebilisim.com/book/glamour-nail',
    status: 'SENT',
    createdAt: `${today} 10:30`,
  },
];
